FONTDIR := tfm

$(OBJDIR)/tfmp_tfm.o: $(FONTDIR)/tfmp_tfm.cc 
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/tfmp_tfm_header.o: $(FONTDIR)/tfmp_tfm_header.cc 
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/tfmp_tfm_data.o: $(FONTDIR)/tfmp_tfm_data.cc 
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/tfmp_tfm_data_header.o: $(FONTDIR)/tfmp_tfm_data_header.cc 
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/tfmp_tfm_data_charinfo.o: $(FONTDIR)/tfmp_tfm_data_charinfo.cc 
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/tfmp_tfmutil.o: $(FONTDIR)/tfmp_tfmutil.cc 
	$(CC) $(CFLAGS) -c -o $@ $<


