PAINTINGDIR := display

$(OBJDIR)/tfmp_display.o: $(PAINTINGDIR)/tfmp_display.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/tfmp_display_board.o: $(PAINTINGDIR)/tfmp_display_board.cc
	$(CC) $(CFLAGS) -c -o $@ $<


